const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cls=s=>({HEALTHY:'healthy',ONLINE:'healthy',DEGRADED:'degraded',FAILED:'failed',OFFLINE:'failed',MAINTENANCE:'maintenance'})[String(s||'UNKNOWN').toUpperCase()]||'unknown';
const seen=new Map();

function injectCss(){if(document.getElementById('kicc-live-console-style'))return;const s=document.createElement('style');s.id='kicc-live-console-style';s.textContent=`
.live-console{display:grid;gap:10px;margin-bottom:10px}.live-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.live-card{border:1px solid #263244;border-radius:11px;background:#111827;padding:10px;min-width:0}.live-card-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.live-card strong{font-size:11px}.live-card small{display:block;color:#64748b;font-size:8px;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.live-lamps{display:flex;align-items:center;gap:7px}.live-led,.traffic-led{width:10px;height:10px;border-radius:50%;background:#64748b}.live-led.healthy{background:#22c55e;box-shadow:0 0 8px rgba(34,197,94,.55)}.live-led.degraded{background:#eab308;box-shadow:0 0 8px rgba(234,179,8,.45)}.live-led.failed{background:#ef4444;box-shadow:0 0 8px rgba(239,68,68,.5)}.traffic-led{background:#3f3f46}.traffic-led.active{background:#facc15;box-shadow:0 0 10px rgba(250,204,21,.8);animation:kiccTraffic .45s ease-in-out 2}.live-metrics{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.live-metric{border:1px solid #263244;border-radius:10px;background:#0f172a;padding:9px}.live-metric small{display:block;color:#64748b;font-size:8px}.live-metric strong{display:block;margin-top:3px;font-size:16px}.live-legend{display:flex;gap:14px;color:#64748b;font-size:8px}.live-legend span{display:flex;align-items:center;gap:5px}@keyframes kiccTraffic{50%{transform:scale(1.35);filter:brightness(1.5)}}@media(max-width:1000px){.live-strip{grid-template-columns:1fr 1fr}.live-metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.live-strip,.live-metrics{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s);}
function statusOf(d){return String(d?.status||d?.health||'UNKNOWN').toUpperCase();}
function trafficActive(id,stamp){if(!stamp)return false;const old=seen.get(id);seen.set(id,stamp);return Boolean(old&&old!==stamp);}
function fmtMs(v){return Number.isFinite(v)?`${Math.round(v)} ms`:'—';}
function fmtPct(a,b){return b?`${((a/b)*100).toFixed(2)} %`:'—';}
function dbCard(d){const active=trafficActive(d.id,d.measuredAt);return `<article class="live-card"><div class="live-card-head"><div><strong>${esc(d.name)}</strong><small>${esc(d.role||'')}</small></div><div class="live-lamps" title="links Status · rechts echter Messverkehr"><span class="live-led ${cls(statusOf(d))}"></span><span class="traffic-led ${active?'active':''}"></span></div></div><small>Status ${esc(statusOf(d))} · Latenz ${esc(fmtMs(d.latencyMs))} · Messung ${esc(d.measuredAt?new Date(d.measuredAt).toLocaleTimeString('de-DE'):'—')}</small></article>`;}
function render(){const host=document.getElementById('kiccLiveConsole');if(!host)return;const dbs=globalThis.KICC?.databases||[];const mirror=globalThis.KICC_MIRROR?.flow||{};const mh=globalThis.KICC_MIRROR?.health?.()||{};const mirrorTraffic=trafficActive('mirror',mirror.lastSuccessAt||mirror.measuredAt);host.innerHTML=`<div class="live-strip">${dbs.map(dbCard).join('')}<article class="live-card"><div class="live-card-head"><div><strong>Supabase → Neon Mirror</strong><small>FLOW · autoritative Telemetrie</small></div><div class="live-lamps"><span class="live-led ${cls(mh.status||mirror.status)}"></span><span class="traffic-led ${mirrorTraffic?'active':''}"></span></div></div><small>${esc(mh.reason||mirror.message||'Noch keine Mirror-Telemetrie')}</small></article></div><div class="live-metrics"><div class="live-metric"><small>Mirror-Läufe 24h</small><strong>${mirror.runCount24h??'—'}</strong></div><div class="live-metric"><small>Fehler 24h</small><strong>${mirror.errorCount24h??'—'}</strong></div><div class="live-metric"><small>Fehlerquote</small><strong>${fmtPct(mirror.errorCount24h,mirror.runCount24h)}</strong></div><div class="live-metric"><small>Mismatches</small><strong>${mirror.mismatchCount24h??'—'}</strong></div><div class="live-metric"><small>Sync-Lag</small><strong>${Number.isFinite(mirror.syncLagSec)?`${mirror.syncLagSec}s`:'—'}</strong></div><div class="live-metric"><small>Failover ready</small><strong>${mh.readyForFailover===true?'JA':mh.readyForFailover===false?'NEIN':'—'}</strong></div></div><div class="live-legend"><span><i class="live-led healthy"></i>Status/Health</span><span><i class="traffic-led active"></i>neue echte Mess-/Sync-Aktivität</span></div>`;}
function mount(){injectCss();const panel=document.querySelector('[data-kicc-panel="live"]');if(!panel||document.getElementById('kiccLiveConsole'))return;const host=document.createElement('section');host.id='kiccLiveConsole';host.className='live-console';const mirrorPanel=panel.querySelector('.panel');panel.insertBefore(host,mirrorPanel);render();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();setInterval(render,3000);addEventListener('kicc:tabchange',e=>{if(e.detail?.tab==='live')setTimeout(render,30)});globalThis.KICC_LIVE_CONSOLE={render,mount};
