const STATUS_MAP={HEALTHY:'healthy',ONLINE:'healthy',DEGRADED:'degraded',WARNING:'degraded',FAILED:'failed',OFFLINE:'failed',MAINTENANCE:'maintenance',TEST:'maintenance',UNKNOWN:'unknown',NOT_APPLICABLE:'unknown'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const statusClass=s=>STATUS_MAP[String(s||'UNKNOWN').toUpperCase()]||'unknown';
const normStatus=s=>String(s||'UNKNOWN').toUpperCase();
const chartMap=new Map();
let resizeObserver=null;

function allPrograms(){return [...(globalThis.KICC_PROGRAMS?.programs||[]),...(globalThis.KICC_NON_KC?.programs||[])];}
function databases(){return globalThis.KICC?.databases||[];}
function health(){try{return globalThis.KICC?.systemHealth?.()||null;}catch{return null;}}
function freshLatency(db){return Number.isFinite(db?.latencyMs)?Math.max(0,Math.round(db.latencyMs)):null;}
function dbStatus(db){return normStatus(db?.status||db?.health||db?.runtimeHealth||'UNKNOWN');}
function programStatus(p){return normStatus(p?.status||p?.runtimeHealth||p?.health||'UNKNOWN');}
function primaryDb(){return databases().find(x=>String(x.role||'').includes('PRIMARY'))||null;}
function neonDb(){return databases().find(x=>String(x.provider||'').toLowerCase()==='neon')||null;}
function mirrorState(){const c=globalThis.KICC?.failoverContext||{};return c.mirrorReady===true?'HEALTHY':c.mirrorReady===false?'DEGRADED':'UNKNOWN';}
function bridgeState(){return normStatus(globalThis.KICC_GIT_BRIDGE?.state==='READY'?'HEALTHY':globalThis.KICC_GIT_BRIDGE?.state==='FAILED'?'FAILED':'UNKNOWN');}
function dashboardVisible(){const panel=document.querySelector('[data-kicc-panel="dashboard"]');return Boolean(panel&&!panel.hidden&&panel.offsetParent!==null);}

function ledItem(label,status,detail=''){const s=normStatus(status);return `<div class="dash-led-item" title="${esc(detail||s)}"><span class="dash-led ${statusClass(s)}"></span><span><strong>${esc(label)}</strong><small>${esc(s)}</small></span></div>`;}
function renderLeds(){const host=document.getElementById('dashboardStatusLeds');if(!host)return;const p=primaryDb(),n=neonDb();const programs=allPrograms(),known=programs.filter(x=>programStatus(x)!=='UNKNOWN');const programState=programs.some(x=>['FAILED','OFFLINE'].includes(programStatus(x)))?'FAILED':programs.some(x=>['DEGRADED','WARNING'].includes(programStatus(x)))?'DEGRADED':programs.length&&known.length===programs.length&&known.every(x=>['HEALTHY','ONLINE'].includes(programStatus(x)))?'HEALTHY':'UNKNOWN';const system=normStatus(health()?.status||'UNKNOWN');host.innerHTML=[ledItem('KC Gesamt',system,'Nur bestätigte KICC-Gesundheit'),ledItem('Programme',programState,`${known.length}/${programs.length} mit bekanntem Runtime-Status`),ledItem('Supabase',p?dbStatus(p):'UNKNOWN',p?.name||'Keine Primärdatenbank'),ledItem('Neon',n?dbStatus(n):'UNKNOWN',n?.name||'Kein Neon-Mirror'),ledItem('Mirror',mirrorState(),'Mirror-Readiness'),ledItem('Git Bridge',bridgeState(),globalThis.KICC_GIT_BRIDGE?.state||'nicht konfiguriert')].join('');}

function svgGauge({value,max=100,label,unit='',unknown=false}){const safe=unknown?0:Math.max(0,Math.min(max,Number(value)||0));const pct=safe/max;const angle=-120+pct*240;const text=unknown?'—':`${Math.round(safe)}${unit}`;return `<div class="svg-gauge"><svg viewBox="0 0 220 150" role="img" aria-label="${esc(label)}"><path class="gauge-track" d="M35 125 A85 85 0 1 1 185 125"/><line class="gauge-needle" x1="110" y1="125" x2="110" y2="52" transform="rotate(${angle} 110 125)"/><circle class="gauge-hub" cx="110" cy="125" r="6"/><text class="gauge-value" x="110" y="106" text-anchor="middle">${esc(text)}</text><text class="gauge-label" x="110" y="145" text-anchor="middle">${esc(label)}</text></svg></div>`;}
function renderGaugeFallback(){const h=health(),coverage=Number.isFinite(h?.coverage)?Math.round(h.coverage):null;const p=primaryDb(),lat=freshLatency(p);const programList=allPrograms(),known=programList.filter(x=>programStatus(x)!=='UNKNOWN').length;const programCoverage=programList.length?Math.round(known/programList.length*100):null;document.getElementById('gaugeCoverage').innerHTML=svgGauge({value:coverage,max:100,label:'Messabdeckung',unit:'%',unknown:coverage==null});document.getElementById('gaugeLatency').innerHTML=svgGauge({value:lat,max:Math.max(500,Math.ceil((lat||0)/100)*100),label:'Primär-DB Latenz',unit:' ms',unknown:lat==null});document.getElementById('gaugePrograms').innerHTML=svgGauge({value:programCoverage,max:100,label:'Programme gemessen',unit:'%',unknown:programCoverage==null});}
function gaugeOption(value,max,label,unit){const unknown=value==null||!Number.isFinite(value);const shown=unknown?0:Math.round(value);return{animationDuration:350,series:[{type:'gauge',min:0,max,splitNumber:5,startAngle:210,endAngle:-30,progress:{show:!unknown,width:8},axisLine:{lineStyle:{width:8}},axisTick:{distance:-12,length:4},splitLine:{distance:-15,length:8},axisLabel:{distance:13,fontSize:9},pointer:{show:!unknown,length:'58%',width:4},anchor:{show:!unknown,size:8},title:{offsetCenter:[0,'72%'],fontSize:11},detail:{valueAnimation:true,offsetCenter:[0,'34%'],fontSize:18,formatter:unknown?'—':`{value}${unit}`},data:[{value:shown,name:label}]}]};}
function chartFor(id){const el=document.getElementById(id);if(!el||!globalThis.echarts)return null;let chart=globalThis.echarts.getInstanceByDom(el)||chartMap.get(id);if(!chart){if(!dashboardVisible()||el.clientWidth<10||el.clientHeight<10)return null;chart=globalThis.echarts.init(el);chartMap.set(id,chart);}return chart;}
function setChart(id,option){const chart=chartFor(id);if(!chart)return false;chart.setOption(option,{notMerge:true,lazyUpdate:false});return true;}
function resizeCharts(){if(!dashboardVisible())return;for(const [id,chart] of [...chartMap]){const el=document.getElementById(id);if(!el||!el.isConnected){try{chart.dispose();}catch{}chartMap.delete(id);continue;}if(el.clientWidth>10&&el.clientHeight>10){try{chart.resize();}catch{}}}}
function useEchartsGauge(id,value,max,label,unit=''){return setChart(id,gaugeOption(value,max,label,unit));}
function renderGauges(){const h=health(),coverage=Number.isFinite(h?.coverage)?Math.round(h.coverage):null;const p=primaryDb(),lat=freshLatency(p);const ps=allPrograms(),known=ps.filter(x=>programStatus(x)!=='UNKNOWN').length,pc=ps.length?Math.round(known/ps.length*100):null;if(!globalThis.echarts){renderGaugeFallback();return;}if(!dashboardVisible())return;useEchartsGauge('gaugeCoverage',coverage,100,'Messabdeckung','%');useEchartsGauge('gaugeLatency',lat,Math.max(500,Math.ceil((lat||0)/100)*100),'Primär-DB Latenz',' ms');useEchartsGauge('gaugePrograms',pc,100,'Programme gemessen','%');}

function renderStatusDistribution(){const host=document.getElementById('statusDistributionChart');if(!host)return;const items=[...allPrograms(),...databases()];const counts={HEALTHY:0,DEGRADED:0,FAILED:0,UNKNOWN:0};items.forEach(x=>{const s=x.type==='DATABASE'?dbStatus(x):programStatus(x);if(['HEALTHY','ONLINE'].includes(s))counts.HEALTHY++;else if(['DEGRADED','WARNING'].includes(s))counts.DEGRADED++;else if(['FAILED','OFFLINE'].includes(s))counts.FAILED++;else counts.UNKNOWN++;});if(globalThis.echarts){if(!dashboardVisible())return;setChart('statusDistributionChart',{animationDuration:300,grid:{left:82,right:26,top:12,bottom:22},xAxis:{type:'value',minInterval:1,axisLabel:{fontSize:9}},yAxis:{type:'category',data:['Gesund','Warnung','Fehler','Unbekannt'],axisLabel:{fontSize:10}},series:[{type:'bar',barMaxWidth:22,data:[counts.HEALTHY,counts.DEGRADED,counts.FAILED,counts.UNKNOWN],label:{show:true,position:'right'}}]});return;}host.innerHTML=`<div class="fallback-bars">${Object.entries(counts).map(([k,v])=>`<div><span>${esc(k)}</span><b style="--v:${Math.max(2,v*14)}px"></b><strong>${v}</strong></div>`).join('')}</div>`;}
function renderLatencyChart(){const host=document.getElementById('databaseLatencyChart');if(!host)return;const rows=databases().map(d=>({name:d.name,value:freshLatency(d)})).filter(x=>x.value!=null);if(!rows.length){host.innerHTML='<div class="chart-empty">Noch keine bestätigten Latenzmessungen.</div>';return;}if(globalThis.echarts){if(!dashboardVisible())return;setChart('databaseLatencyChart',{animationDuration:300,grid:{left:135,right:48,top:12,bottom:22},xAxis:{type:'value',name:'ms',axisLabel:{fontSize:9}},yAxis:{type:'category',data:rows.map(x=>x.name.replace(/^.*?·\s*/,'')),axisLabel:{fontSize:9,width:115,overflow:'truncate'}},series:[{type:'bar',barMaxWidth:22,data:rows.map(x=>x.value),label:{show:true,position:'right',formatter:'{c} ms'}}]});return;}host.innerHTML=`<div class="fallback-latency">${rows.map(x=>`<div><span>${esc(x.name)}</span><b style="width:${Math.min(100,x.value/5)}%"></b><strong>${Math.round(x.value)} ms</strong></div>`).join('')}</div>`;}

function render(){renderLeds();if(!dashboardVisible())return;renderGauges();renderStatusDistribution();renderLatencyChart();requestAnimationFrame(resizeCharts);}
function schedule(){setTimeout(render,100);setTimeout(()=>{render();resizeCharts();},900);}
function onTabChange(e){if(e?.detail?.tab!=='dashboard')return;requestAnimationFrame(()=>requestAnimationFrame(()=>{render();resizeCharts();}));setTimeout(()=>{render();resizeCharts();},250);}
window.addEventListener('resize',resizeCharts);
window.addEventListener('orientationchange',()=>setTimeout(resizeCharts,150));
window.addEventListener('kicc:tabchange',onTabChange);
if('ResizeObserver'in globalThis){resizeObserver=new ResizeObserver(()=>requestAnimationFrame(resizeCharts));const host=document.getElementById('dashboardInstruments');if(host)resizeObserver.observe(host);}
globalThis.KICC_DASHBOARD_INSTRUMENTS={render,schedule,resize:resizeCharts};schedule();setInterval(render,15000);
