import './live-topology.js';
const STATUS_MAP={HEALTHY:'healthy',ONLINE:'healthy',OK:'healthy',CONNECTED:'healthy',DEGRADED:'degraded',WARNING:'degraded',WARN:'degraded',FAILED:'failed',OFFLINE:'failed',ERROR:'failed',DISCONNECTED:'failed',MAINTENANCE:'maintenance',TEST:'maintenance',RUNNING:'maintenance',UNKNOWN:'unknown',NOT_APPLICABLE:'unknown'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'UNKNOWN').toUpperCase();
const cls=s=>STATUS_MAP[norm(s)]||'unknown';
function programs(){return [...(globalThis.KICC_PROGRAMS?.programs||[]),...(globalThis.KICC_NON_KC?.programs||[])];}
function dbs(){return globalThis.KICC?.databases||[];}
function health(){try{return globalThis.KICC?.systemHealth?.()||null;}catch{return null;}}
function dbEvidence(d){if(!d?.id)return null;try{return (globalThis.KICC?.telemetry?.()||[]).find(x=>x.id===d.id)||null;}catch{return null;}}
function dbStatus(d){const e=dbEvidence(d);return e?norm(e.status):'UNKNOWN';}
function programEvidence(p){const api=globalThis.KICC_PROGRAM_HEARTBEATS;if(!p?.id||!api?.evidence)return null;try{return api.evidence(p.id);}catch{return null;}}
function programStatus(p){const e=programEvidence(p);return e?.fresh?norm(e.status):'UNKNOWN';}
function latency(d){const e=dbEvidence(d);return Number.isFinite(e?.latencyMs)?Math.max(0,Math.round(e.latencyMs)):null;}
function primary(){return dbs().find(x=>String(x.role||'').includes('PRIMARY'))||null;}
function neon(){return dbs().find(x=>String(x.provider||'').toLowerCase()==='neon')||null;}
function indexed(){return dbs().find(x=>String(x.provider||'').toLowerCase()==='indexeddb')||null;}
function mirrorState(){const c=globalThis.KICC?.failoverContext||{};return c.mirrorReady===true?'HEALTHY':c.mirrorReady===false?'DEGRADED':'UNKNOWN';}
function bridgeState(){return norm(globalThis.KICC_GIT_BRIDGE?.state==='READY'?'HEALTHY':globalThis.KICC_GIT_BRIDGE?.state==='FAILED'?'FAILED':'UNKNOWN');}
function visible(){const p=document.querySelector('[data-kicc-panel="dashboard"]');return !!(p&&!p.hidden);}
function pctFromStatus(s){return ['HEALTHY','ONLINE','OK','CONNECTED'].includes(norm(s))?100:['DEGRADED','WARNING','WARN'].includes(norm(s))?66:['FAILED','OFFLINE','ERROR','DISCONNECTED'].includes(norm(s))?18:0;}
function ensure(){const host=document.getElementById('dashboardInstruments');if(!host)return false;if(host.querySelector('[data-kicc-instrument-root]'))return true;host.innerHTML=`<section class="dashboard-instruments kcui-dashboard" data-kicc-instrument-root><div id="dashboardStatusLeds" class="dash-led-strip"></div><div class="instrument-grid kcui-grid"><article class="instrument-card kcui-speed"><div class="instrument-card-head"><strong>Speed Pro</strong><span>Primär-DB Latenz</span></div><div id="kcuiSpeed" class="gauge-host"></div></article><article class="instrument-card kcui-half"><div class="instrument-card-head"><strong>Compact Half Gauge</strong><span>Messabdeckung</span></div><div id="kcuiCoverage" class="gauge-host"></div></article><article class="instrument-card kcui-progress"><div class="instrument-card-head"><strong>Progress Ring</strong><span>Programme gemessen</span></div><div id="kcuiPrograms" class="gauge-host"></div></article><article class="instrument-card kcui-multiring"><div class="instrument-card-head"><strong>Multi-Ring</strong><span>Supabase · Neon · Local</span></div><div id="kcuiMultiRing" class="gauge-host"></div></article><article class="instrument-card chart-wide"><div class="instrument-card-head"><strong>Säulen Pro</strong><span>Datenbank-Latenzen</span></div><div id="kcuiBars" class="chart-host"></div></article><article class="instrument-card chart-wide"><div class="instrument-card-head"><strong>Donut</strong><span>Statusverteilung</span></div><div id="kcuiDonut" class="chart-host"></div></article></div><div class="instrument-truth-note">KC Shared UI 0.2.0 · Programmanzeigen nur aus frischen Heartbeats · Datenbanken nur aus frischer Runtime-Telemetrie · UNKNOWN bleibt UNKNOWN.</div></section>`;return true;}
function led(label,status,detail=''){const s=norm(status);return `<div class="dash-led-item" title="${esc(detail||s)}"><span class="dash-led ${cls(s)}"></span><span><strong>${esc(label)}</strong><small>${esc(s)}</small></span></div>`;}
function renderLeds(){const h=document.getElementById('dashboardStatusLeds');if(!h)return;const ps=programs(),known=ps.filter(p=>programStatus(p)!=='UNKNOWN'),pstate=ps.some(p=>['FAILED','OFFLINE','ERROR','DISCONNECTED'].includes(programStatus(p)))?'FAILED':ps.some(p=>['DEGRADED','WARNING','WARN'].includes(programStatus(p)))?'DEGRADED':ps.length&&known.length===ps.length?'HEALTHY':'UNKNOWN';h.innerHTML=[led('KC Gesamt',health()?.status),led('Programme',pstate,`${known.length}/${ps.length} mit frischem Heartbeat`),led('Supabase',primary()?dbStatus(primary()):'UNKNOWN'),led('Neon',neon()?dbStatus(neon()):'UNKNOWN'),led('Mirror',mirrorState()),led('Git Bridge',bridgeState())].join('');}
function speedGauge(value){const unknown=value==null,max=200,safe=unknown?0:Math.min(max,Math.max(0,value)),a=-125+(safe/max)*250,ticks=Array.from({length:11},(_,i)=>-125+i*25);return `<div class="kcui-speedpro"><svg viewBox="0 0 240 180"><path class="kcui-speed-arc-bg" d="M35 142 A88 88 0 1 1 205 142"/><path class="kcui-speed-arc" d="M35 142 A88 88 0 1 1 205 142"/>${ticks.map((t,i)=>`<line class="kcui-speed-tick ${i%2===0?'major':''}" x1="120" y1="48" x2="120" y2="${i%2===0?61:57}" transform="rotate(${t} 120 142)"/>`).join('')}<line class="kcui-speed-needle" x1="120" y1="142" x2="120" y2="70" transform="rotate(${a} 120 142)"/><circle class="kcui-speed-hub" cx="120" cy="142" r="10"/><text class="kcui-big-value" x="120" y="118" text-anchor="middle">${unknown?'—':Math.round(value)+' ms'}</text><text class="kcui-caption" x="120" y="170" text-anchor="middle">Antwortzeit</text></svg></div>`;}
function halfGauge(value){const unknown=value==null,v=unknown?0:Math.max(0,Math.min(100,value)),dash=251.3*(v/100);return `<div class="kcui-halfgauge"><svg viewBox="0 0 220 145"><path class="kcui-half-bg" d="M30 120 A80 80 0 0 1 190 120"/><path class="kcui-half-progress" stroke-dasharray="${dash} 251.3" d="M30 120 A80 80 0 0 1 190 120"/><text class="kcui-half-value" x="110" y="96" text-anchor="middle">${unknown?'—':Math.round(v)+'%'}</text><text class="kcui-caption" x="110" y="125" text-anchor="middle">Systemabdeckung</text></svg></div>`;}
function progressRing(value){const unknown=value==null,v=unknown?0:Math.max(0,Math.min(100,value)),r=62,c=2*Math.PI*r,d=c*(v/100);return `<div class="kcui-progressring"><svg viewBox="0 0 180 180"><circle class="kcui-ring-bg" cx="90" cy="82" r="${r}"/><circle class="kcui-ring-progress" cx="90" cy="82" r="${r}" stroke-dasharray="${d} ${c-d}"/><text class="kcui-ring-value" x="90" y="89" text-anchor="middle">${unknown?'—':Math.round(v)+'%'}</text><text class="kcui-caption" x="90" y="160" text-anchor="middle">Heartbeat-Abdeckung</text></svg></div>`;}
function multiRing(){const src=[{name:'Supabase',s:primary()?dbStatus(primary()):'UNKNOWN',r:72,c:'ok'},{name:'Neon',s:neon()?dbStatus(neon()):'UNKNOWN',r:55,c:'blue'},{name:'Local',s:indexed()?dbStatus(indexed()):'UNKNOWN',r:38,c:'violet'}],vals=src.map(x=>({...x,v:pctFromStatus(x.s)})),known=src.filter(x=>norm(x.s)!=='UNKNOWN'),center=known.length?`${Math.round(known.reduce((a,x)=>a+pctFromStatus(x.s),0)/known.length)}%`:'—';return `<div class="kcui-multiring-wrap"><svg viewBox="0 0 220 190">${vals.map(x=>{const circ=2*Math.PI*x.r,d=circ*x.v/100;return `<circle class="kcui-multi-bg" cx="110" cy="88" r="${x.r}"/><circle class="kcui-multi ${x.c}" cx="110" cy="88" r="${x.r}" stroke-dasharray="${d} ${circ-d}"/>`;}).join('')}<text class="kcui-multi-center" x="110" y="94" text-anchor="middle">${center}</text><text class="kcui-caption" x="110" y="180" text-anchor="middle">Supabase · Neon · Local</text></svg></div>`;}
function bars(){const host=document.getElementById('kcuiBars');if(!host)return;const rows=dbs().map(d=>({n:d.name.replace(/^.*?·\s*/,''),v:latency(d)})).filter(x=>x.v!=null);if(!rows.length){host.innerHTML='<div class="chart-empty">Noch keine bestätigten Latenzmessungen.</div>';return;}const max=Math.max(1,...rows.map(x=>x.v));host.innerHTML=`<div class="kcui-column-chart">${rows.map(x=>`<div class="kcui-col"><strong>${Math.round(x.v)}<small> ms</small></strong><div class="kcui-col-track"><i style="height:${Math.max(4,x.v/max*100)}%"></i></div><span title="${esc(x.n)}">${esc(x.n)}</span></div>`).join('')}</div>`;}
function donut(){const host=document.getElementById('kcuiDonut');if(!host)return;const items=[...programs().map(x=>({kind:'PROGRAM',x})),...dbs().map(x=>({kind:'DATABASE',x}))],c={ok:0,warn:0,bad:0,unknown:0};items.forEach(({kind,x})=>{const s=kind==='DATABASE'?dbStatus(x):programStatus(x);if(['HEALTHY','ONLINE','OK','CONNECTED'].includes(s))c.ok++;else if(['DEGRADED','WARNING','WARN'].includes(s))c.warn++;else if(['FAILED','OFFLINE','ERROR','DISCONNECTED'].includes(s))c.bad++;else c.unknown++;});const total=Math.max(1,c.ok+c.warn+c.bad+c.unknown),a=c.ok/total*360,b=(c.ok+c.warn)/total*360,d=(c.ok+c.warn+c.bad)/total*360;host.innerHTML=`<div class="kcui-donut-row"><div class="kcui-donut" style="--a:${a}deg;--b:${b}deg;--d:${d}deg"><span>${c.ok+c.warn+c.bad}<small>bekannt</small></span></div><div class="kcui-donut-legend"><span><i class="ok"></i>Gesund <b>${c.ok}</b></span><span><i class="warn"></i>Warnung <b>${c.warn}</b></span><span><i class="bad"></i>Fehler <b>${c.bad}</b></span><span><i class="unknown"></i>Unbekannt <b>${c.unknown}</b></span></div></div>`;}
function render(){if(!ensure())return;renderLeds();if(!visible())return;const h=health(),coverage=Number.isFinite(h?.coverage)?Math.round(h.coverage):null,p=primary(),lat=latency(p),ps=programs(),known=ps.filter(x=>programStatus(x)!=='UNKNOWN').length,pc=ps.length?Math.round(known/ps.length*100):null;document.getElementById('kcuiSpeed').innerHTML=speedGauge(lat);document.getElementById('kcuiCoverage').innerHTML=halfGauge(coverage);document.getElementById('kcuiPrograms').innerHTML=progressRing(pc);document.getElementById('kcuiMultiRing').innerHTML=multiRing();bars();donut();}
function schedule(){setTimeout(render,50);setTimeout(render,450);setTimeout(render,1200);}window.addEventListener('resize',()=>requestAnimationFrame(render));window.addEventListener('orientationchange',()=>setTimeout(render,150));window.addEventListener('kicc:tabchange',e=>{if(e?.detail?.tab==='dashboard'){requestAnimationFrame(render);setTimeout(render,120);}});['kicc:program-flow-ingested','kicc:network-snapshot','kicc:mirror-telemetry','kicc:program-heartbeat-ingested'].forEach(name=>window.addEventListener(name,()=>requestAnimationFrame(render)));globalThis.KICC_DASHBOARD_INSTRUMENTS={render,schedule,ensureStructure:ensure,programStatus,programEvidence,dbStatus,dbEvidence};schedule();setInterval(render,5000);