const ENDPOINT='http://127.0.0.1:8765/v1/network';
const MAX_POINTS=180;
const history=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,suffix='—')=>Number.isFinite(Number(v))?`${Math.round(Number(v)*10)/10}${suffix?` ${suffix}`:''}`:'—';
const age=iso=>{if(!iso)return'—';const ms=Date.now()-new Date(iso).getTime();if(!Number.isFinite(ms))return'—';if(ms<5000)return'gerade eben';if(ms<60000)return`${Math.round(ms/1000)} s`;return`${Math.round(ms/60000)} min`;};
let last=null,charts={};
function stateClass(status){const s=String(status||'').toUpperCase();if(['OK','ONLINE','HEALTHY'].includes(s))return'ok';if(['DEGRADED','WARN','WARNING'].includes(s))return'warn';if(['FAILED','ERROR','OFFLINE'].includes(s))return'bad';return'';}
function pushHistory(s){if(!s?.measuredAt)return;const t=new Date(s.measuredAt).getTime();if(!Number.isFinite(t))return;if(history.some(x=>x.t===t))return;history.push({t,latencyMs:Number(s.internet?.latencyMs),jitterMs:Number(s.internet?.jitterMs),packetLossPct:Number(s.internet?.packetLossPct),dnsMs:Number(s.internet?.dnsMs),httpMs:Number(s.internet?.httpMs),downMbps:Number(s.wan?.currentDownMbps),upMbps:Number(s.wan?.currentUpMbps)});history.sort((a,b)=>a.t-b.t);if(history.length>MAX_POINTS)history.splice(0,history.length-MAX_POINTS);}
function card(id,title,sub){return `<section class="internet-card"><div class="internet-card-head"><h3>${esc(title)}</h3><span>${esc(sub)}</span></div><div id="${id}" class="internet-chart"><div class="internet-empty">Noch keine reale Messung.</div></div></section>`;}
function mount(){const root=document.getElementById('internetMonitor');if(!root)return;root.className='internet-monitor';root.innerHTML=`<div id="internetAgentState" class="internet-agent-state"><span class="led"></span><div><b>KC Local Agent nicht verbunden</b><small>Keine Simulation · Werte erscheinen erst bei realen Messungen.</small></div></div><div id="internetKpis" class="internet-statusbar"></div><div class="internet-grid">${card('internetLatencyChart','Latenz & Jitter','ms · Verlauf')}${card('internetLossChart','Paketverlust','% · reale ICMP/Probe-Messung')}${card('internetDnsHttpChart','DNS & HTTP','ms · Namensauflösung und Web-Handshake')}${card('internetTrafficChart','WAN-Datenrate','Mbit/s · nur wenn Router/Agent liefert')}<section class="internet-card wide"><div class="internet-card-head"><h3>FRITZ!Box / WAN Details</h3><span>TR-064 bzw. lokaler Agent</span></div><div id="internetRouterDetails" class="internet-detail-grid"><div class="internet-empty">Noch keine Routerdaten.</div></div></section><section class="internet-card wide"><div class="internet-card-head"><h3>Live-Status</h3><span>Internet → FRITZ!Box → Bridge</span></div><div id="internetLedRow" class="internet-led-row"></div></section></div>`;}
function kpis(s){const i=s?.internet||{},w=s?.wan||{};const items=[['Internet',s?.status||'UNKNOWN','Gesamtzustand'],['Latenz',fmt(i.latencyMs,'ms'),'Median/aktuell'],['Jitter',fmt(i.jitterMs,'ms'),'Schwankung'],['Paketverlust',fmt(i.packetLossPct,'%'),'letzte Messung'],['Download',fmt(w.currentDownMbps,'Mbit/s'),'aktuelle WAN-Rate'],['Upload',fmt(w.currentUpMbps,'Mbit/s'),'aktuelle WAN-Rate']];document.getElementById('internetKpis').innerHTML=items.map(([a,b,c])=>`<div class="internet-kpi"><small>${esc(a)}</small><strong>${esc(b)}</strong><span>${esc(c)}</span></div>`).join('');}
function details(s){const r=s?.router||{},w=s?.wan||{},i=s?.internet||{};const rows=[['Gerät',r.model||r.name],['FRITZ!OS',r.firmware],['Router-IP',r.lanIp],['Erreichbar',r.reachable===true?'Ja':r.reachable===false?'Nein':null],['WAN-Status',w.status],['Öffentliche IP',w.publicIp],['WAN seit',w.uptimeSeconds!=null?`${Math.round(w.uptimeSeconds/60)} min`:null],['Leitung Down',Number.isFinite(Number(w.maxDownMbps))?`${w.maxDownMbps} Mbit/s`:null],['Leitung Up',Number.isFinite(Number(w.maxUpMbps))?`${w.maxUpMbps} Mbit/s`:null],['DNS',Number.isFinite(Number(i.dnsMs))?`${i.dnsMs} ms`:null],['HTTP/TLS',Number.isFinite(Number(i.httpMs))?`${i.httpMs} ms`:null],['Messung',s?.measuredAt?new Date(s.measuredAt).toLocaleString('de-DE'):null]];document.getElementById('internetRouterDetails').innerHTML=rows.filter(x=>x[1]!==undefined&&x[1]!==null&&x[1]!=='').map(([a,b])=>`<div class="internet-detail"><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('')||'<div class="internet-empty">Noch keine Routerdaten.</div>';}
function leds(s){const l=[['Internet',s?.internet?.status||s?.status],['FRITZ!Box',s?.router?.status],['WAN',s?.wan?.status],['LAN',s?.lan?.status],['WLAN',s?.wifi?.status],['KC Bridge',s?.bridge?.status]];document.getElementById('internetLedRow').innerHTML=l.map(([n,v])=>`<span class="internet-led ${stateClass(v)}"><i></i>${esc(n)} · ${esc(v||'UNKNOWN')}</span>`).join('');}
function chart(id,series,yName){const el=document.getElementById(id);if(!el||!globalThis.echarts)return;charts[id]??=echarts.init(el);const data=history.map(x=>x.t);charts[id].setOption({animation:false,backgroundColor:'transparent',tooltip:{trigger:'axis'},legend:{textStyle:{color:'#aabccb'}},grid:{left:45,right:16,top:34,bottom:34},xAxis:{type:'category',data:data.map(t=>new Date(t).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'})),axisLabel:{color:'#7f96aa',hideOverlap:true},axisLine:{lineStyle:{color:'#2a4054'}}},yAxis:{type:'value',name:yName,nameTextStyle:{color:'#7f96aa'},axisLabel:{color:'#7f96aa'},splitLine:{lineStyle:{color:'#1e3040'}}},series:series.map(([name,key])=>({name,type:'line',showSymbol:false,smooth:true,connectNulls:false,data:history.map(x=>Number.isFinite(x[key])?x[key]:null)}))});}
function render(s){if(!document.getElementById('internetMonitor'))return;last=s;pushHistory(s);const as=document.getElementById('internetAgentState');const fresh=s?.measuredAt&&Date.now()-new Date(s.measuredAt).getTime()<20000;as.className=`internet-agent-state ${fresh?'ok':'warn'}`;as.innerHTML=`<span class="led"></span><div><b>${fresh?'KC Local Agent verbunden':'Messung veraltet'}</b><small>Letzte reale Messung: ${esc(age(s?.measuredAt))}</small></div>`;kpis(s);details(s);leds(s);chart('internetLatencyChart',[['Latenz','latencyMs'],['Jitter','jitterMs']],'ms');chart('internetLossChart',[['Paketverlust','packetLossPct']],'%');chart('internetDnsHttpChart',[['DNS','dnsMs'],['HTTP/TLS','httpMs']],'ms');chart('internetTrafficChart',[['Download','downMbps'],['Upload','upMbps']],'Mbit/s');}
async function poll(){try{const r=await fetch(ENDPOINT,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const s=await r.json();globalThis.dispatchEvent(new CustomEvent('kicc:network-snapshot',{detail:s}));render(s);}catch{const as=document.getElementById('internetAgentState');if(as){as.className='internet-agent-state bad';as.innerHTML='<span class="led"></span><div><b>KC Local Agent nicht erreichbar</b><small>Keine Messwerte erfunden. Agent muss lokal auf diesem PC laufen.</small></div>';}}}
function boot(){mount();addEventListener('kicc:network-snapshot',e=>render(e.detail));addEventListener('resize',()=>Object.values(charts).forEach(c=>c?.resize?.()));poll();setInterval(poll,5000);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();globalThis.KICC_INTERNET_MONITOR={render,poll,get last(){return last},history};