const STORE='kicc.performance.history.v1';
const PERIODS=Object.freeze({LIVE:15*60e3,H1:60*60e3,H24:24*60*60e3,D7:7*24*60*60e3,D30:30*24*60*60e3,Y1:365*24*60*60e3});
const POLICY=Object.freeze({veryFast:80,fast:150,normal:300,slow:800});
let period='H1';
let history=load();

function load(){try{const v=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(v)?v:[];}catch{return[];}}
function save(){try{localStorage.setItem(STORE,JSON.stringify(history));}catch{}}
function rating(ms){if(!Number.isFinite(ms))return{label:'Unbekannt',cls:'unknown'};if(ms<=POLICY.veryFast)return{label:'Sehr schnell',cls:'healthy'};if(ms<=POLICY.fast)return{label:'Schnell',cls:'healthy'};if(ms<=POLICY.normal)return{label:'Normal',cls:'degraded'};if(ms<=POLICY.slow)return{label:'Langsam',cls:'degraded'};return{label:'Kritisch',cls:'failed'};}
function sourceRows(){try{return(globalThis.KICC?.telemetry?.()||[]).filter(x=>Number.isFinite(Number(x.latencyMs))).map(x=>({id:x.id,name:(globalThis.KICC?.databases||[]).find(d=>d.id===x.id)?.name||x.id,latencyMs:Number(x.latencyMs),measuredAt:x.measuredAt||new Date().toISOString(),trust:x.trust||'UNVERIFIED'}));}catch{return[];}}
function bucketSize(age){if(age<=60*60e3)return 60e3;if(age<=24*60*60e3)return 5*60e3;if(age<=30*24*60*60e3)return 60*60e3;return 24*60*60e3;}
function compact(){const now=Date.now(),cut=now-PERIODS.Y1,groups=new Map();for(const s of history){const t=new Date(s.t).getTime();if(!Number.isFinite(t)||t<cut)continue;const b=bucketSize(now-t),slot=Math.floor(t/b)*b,key=`${s.id}|${slot}`;const g=groups.get(key)||{id:s.id,name:s.name,t:new Date(slot).toISOString(),sum:0,n:0,min:Infinity,max:-Infinity,trust:s.trust};g.sum+=Number(s.v)||0;g.n++;g.min=Math.min(g.min,Number(s.v)||0);g.max=Math.max(g.max,Number(s.v)||0);if(s.trust)g.trust=s.trust;groups.set(key,g);}history=[...groups.values()].map(g=>({id:g.id,name:g.name,t:g.t,v:Math.round(g.sum/g.n),min:Math.round(g.min),max:Math.round(g.max),n:g.n,trust:g.trust})).sort((a,b)=>new Date(a.t)-new Date(b.t));if(history.length>12000)history=history.slice(-12000);save();}
function sample(){const now=new Date().toISOString();for(const r of sourceRows())history.push({id:r.id,name:r.name,t:r.measuredAt||now,v:Math.round(r.latencyMs),min:Math.round(r.latencyMs),max:Math.round(r.latencyMs),n:1,trust:r.trust});compact();render();}
function rangeRows(){const from=Date.now()-(PERIODS[period]||PERIODS.H1);return history.filter(x=>new Date(x.t).getTime()>=from);}
function stats(rows){if(!rows.length)return null;const vals=rows.map(x=>Number(x.v)).filter(Number.isFinite).sort((a,b)=>a-b);if(!vals.length)return null;const avg=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length),p95=vals[Math.min(vals.length-1,Math.floor(vals.length*.95))];return{avg,p95,min:vals[0],max:vals[vals.length-1],count:vals.length};}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureCss(){if(document.querySelector('[data-kicc-performance-css]'))return;const s=document.createElement('style');s.dataset.kiccPerformanceCss='1';s.textContent=`.perf-toolbar{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 10px}.perf-toolbar button{border:1px solid #334155;background:#101827;color:#cbd5e1;border-radius:8px;padding:6px 10px;cursor:pointer}.perf-toolbar button.active{background:#1d4ed8;color:white;border-color:#3b82f6}.perf-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;margin-bottom:10px}.perf-card{background:#101827;border:1px solid #26364d;border-radius:10px;padding:10px}.perf-card small{color:#94a3b8;display:block}.perf-card strong{display:block;font-size:19px;margin-top:3px}.perf-chart{height:220px;background:#0b1220;border:1px solid #26364d;border-radius:10px;padding:8px;overflow:hidden}.perf-chart svg{width:100%;height:100%}.perf-legend{display:flex;gap:12px;flex-wrap:wrap;margin-top:8px;color:#94a3b8;font-size:12px}.perf-table{margin-top:10px}.perf-note{font-size:12px;color:#94a3b8;margin-top:8px}`;document.head.appendChild(s);}
function ensureUi(){let panel=document.querySelector('[data-kicc-panel="performance"]');if(panel)return panel;const nav=document.querySelector('[data-kicc-tablist]');const dbBtn=nav?.querySelector('[data-kicc-tab="databases"]');if(nav&&!nav.querySelector('[data-kicc-tab="performance"]')){const b=document.createElement('button');b.className='leitstand-tab';b.dataset.kiccTab='performance';b.setAttribute('role','tab');b.textContent='Performance';dbBtn?.after(b);}const main=document.querySelector('main.shell');if(!main)return null;panel=document.createElement('section');panel.className='tab-panel';panel.dataset.kiccPanel='performance';panel.hidden=true;panel.setAttribute('role','tabpanel');panel.innerHTML=`<div class="tab-intro"><div><h2>Performance</h2><p>Reale Antwortzeiten mit lokaler Verlaufshistorie und einheitlicher Bewertung.</p></div><span class="tab-badge">Observed only</span></div><section class="panel db-panel"><div class="panel-head"><h2>Performance-Center</h2><span>Sehr schnell · Schnell · Normal · Langsam · Kritisch</span></div><div id="performanceCenter"></div></section>`;const dbPanel=document.querySelector('[data-kicc-panel="databases"]');dbPanel?.after(panel);return panel;}
function chart(rows){if(!rows.length)return'<div class="chart-empty">Für diesen Zeitraum liegen noch keine Messwerte vor.</div>';const byId=new Map();for(const r of rows){if(!byId.has(r.id))byId.set(r.id,[]);byId.get(r.id).push(r);}const all=rows.map(x=>Number(x.v)).filter(Number.isFinite),max=Math.max(100,...all),minT=Math.min(...rows.map(x=>new Date(x.t).getTime())),maxT=Math.max(...rows.map(x=>new Date(x.t).getTime()));const W=900,H=210,pad=28,x=t=>pad+((t-minT)/Math.max(1,maxT-minT))*(W-pad*2),y=v=>H-pad-(Math.min(max,v)/max)*(H-pad*2);let paths='',legend='';let idx=0;for(const [id,arr] of byId){arr.sort((a,b)=>new Date(a.t)-new Date(b.t));const d=arr.map((r,i)=>`${i?'L':'M'} ${x(new Date(r.t).getTime()).toFixed(1)} ${y(Number(r.v)).toFixed(1)}`).join(' ');paths+=`<path d="${d}" fill="none" stroke="currentColor" stroke-width="2" opacity="${Math.max(.35,1-idx*.12)}"/>`;legend+=`<span>${esc(arr[0]?.name||id)}</span>`;idx++;}return`<div class="perf-chart"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" stroke="currentColor" opacity=".25"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}" stroke="currentColor" opacity=".25"/>${paths}</svg></div><div class="perf-legend">${legend}</div>`;}
function render(){ensureCss();const panel=ensureUi(),host=panel?.querySelector('#performanceCenter');if(!host)return;const rows=rangeRows(),st=stats(rows),r=rating(st?.avg);const labels={LIVE:'Live',H1:'1 h',H24:'24 h',D7:'7 Tage',D30:'30 Tage',Y1:'Jahr'};const per=[...new Set(rows.map(x=>x.id))].map(id=>{const rr=rows.filter(x=>x.id===id),s=stats(rr),q=rating(s?.avg);return{id,name:rr[0]?.name||id,...s,rating:q};}).filter(x=>x.count);host.innerHTML=`<div class="perf-toolbar">${Object.keys(labels).map(k=>`<button data-perf-period="${k}" class="${period===k?'active':''}">${labels[k]}</button>`).join('')}</div><div class="perf-summary"><div class="perf-card"><small>Durchschnitt</small><strong>${st?st.avg+' ms':'—'}</strong></div><div class="perf-card"><small>95. Perzentil</small><strong>${st?st.p95+' ms':'—'}</strong></div><div class="perf-card"><small>Spanne</small><strong>${st?st.min+'–'+st.max+' ms':'—'}</strong></div><div class="perf-card"><small>Bewertung</small><strong class="${r.cls}">${r.label}</strong></div></div>${chart(rows)}<div class="table-wrap perf-table"><table><thead><tr><th>Quelle</th><th>Ø</th><th>P95</th><th>Min</th><th>Max</th><th>Messpunkte</th><th>Bewertung</th></tr></thead><tbody>${per.length?per.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.avg} ms</td><td>${x.p95} ms</td><td>${x.min} ms</td><td>${x.max} ms</td><td>${x.count}</td><td><span class="status-chip ${x.rating.cls}"><span class="dot"></span>${x.rating.label}</span></td></tr>`).join(''):'<tr><td colspan="7">Noch keine Messwerte im gewählten Zeitraum.</td></tr>'}</tbody></table></div><div class="perf-note">Verlauf aktuell lokal im KICC-Browser gespeichert und automatisch verdichtet. Keine erfundenen Werte. Bewertungs-Policy: ≤80 ms sehr schnell, ≤150 ms schnell, ≤300 ms normal, ≤800 ms langsam, darüber kritisch.</div>`;host.querySelectorAll('[data-perf-period]').forEach(b=>b.onclick=()=>{period=b.dataset.perfPeriod;render();});}
function start(){ensureUi();render();sample();setInterval(sample,60_000);globalThis.addEventListener('kicc:tabchange',e=>{if(e.detail?.tab==='performance')render();});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
globalThis.KICC_PERFORMANCE={render,sample,rating,policy:POLICY,history:()=>[...history],period:()=>period};
